### ISSUE TITLE
アプリ詳細画面の作成

### ISSUE THREAD

**Issue by FNYukii** [Kinoshita0623/Appforum#13]
### 概要
- /app/Http/Controllersディレクトリに、appDetailController.phpを作成する。
- /resources/views/pages/appディレクトリに、appDetail.blade.phpを作成する。

### パス
/apps/{appId}/

**Comment by pantasystem** [comment]
ControllerはAppControllerでOKです
パスはOKです。
bladeの名称もshow.blade.phpがいいと思います。

**Comment by pantasystem** [comment]
Controllerのメソッド名はshowでいいと思います

**Comment by FNYukii** [comment]
了解しました。作業に取り掛かります。

**Comment by pantasystem** [comment]
https://qiita.com/ntm718/items/009c9e611b5c88c1ec3b
LaravelでMarkdown

**Comment by pantasystem** [comment]
余裕ができたらアプリ・サービス一覧からアプリ詳細へ遷移できるようにしてください。
